### ISSUE TITLE
Robinson-Foulds or other

### ISSUE THREAD

**Issue by lskatz** [evolbioinfo/gotree#10]
Hi, I am a big fan of `gotree`!

Are there any plans to have a Robinson-Foulds distance?  Kendall-Colijn?

I _think_ that I can use `gotree compare distances` but the output is so verbose and so I do not know how I will convert that spreadsheet to a summary statistic.

**Comment by fredericlemoine** [comment]
Hi, 
Thank you for your comment.
It is possible to compute RF distance using the output of `gotree compare trees` command. 
Just add column 2 (# branches unique to -i tree) and column 4 (# branches unique to -c tree). Column 3 corresponds to # branches present in both trees.
I just added the option `--rf` that only outputs the addition of the two values.
For the Kendall-Colijn, I am afraid I won't have time to implement it in the near future.

**Comment by lskatz** [comment]
Yay thank you!!!
