### ISSUE TITLE
Output list of taxon labels?

### ISSUE THREAD

**Issue by tseemann** [evolbioinfo/gotree#13]
I want to emulate `nw_labels -I` whicj prints each tip label (not internal nodes) labels one per line.

But I have looked many times over but can not see how to do this in gotree.

Hope you can point me in the right direction.

So `((A,B),C(` woukld print
```
A
B
C
```

**Comment by fredericlemoine** [comment]
Hi, 

Would `gotree stats tips` work?
You should select the 4th column, and maybe remove the header : `gotree stats tips -i <tree> | cut -f 4 | tail -n+2`

**Comment by tseemann** [comment]
Yes, that does work, thank you.

I will use that in my script for now.

But I tjink listing all tap or internal labels is a standard/fundamental operation that deserves its own `labels` command perhaps.

**Comment by fredericlemoine** [comment]
I just added the "labels" command, it works like that:

```
$ echo "((Tip4,(Tip7,Tip2)),Tip0,((Tip8,(Tip9,Tip3)),((Tip6,Tip5),Tip1)));" | gotree labels
Tip4
Tip7
Tip2
Tip0
Tip8
Tip9
Tip3
Tip6
Tip5
Tip1
```
