### ISSUE TITLE
Version string not displayed

### ISSUE THREAD

**Issue by andersgs** [evolbioinfo/gotree#14]
Hello.

Thank you for gotree.

At the moment, the installation of version 0.4.0 from Bioconda seems to have a bug where the version string is not displayed:

```
% gotree version

```

I am wondering if this an issue with how Bioconda is producing the binary, or is this a real bug? I noticed that the version string is generated at compile time (I think --- if I read the code correctly).

Thank you.

Anders.

**Comment by fredericlemoine** [comment]
Dear Anders,
 
Thank you for noticing this error. I just corrected the bioconda recipe, and created a pull request:
https://github.com/bioconda/bioconda-recipes/pull/27211
Hopefully it should be resolved soon.
Thanks,

Frederic

**Comment by fredericlemoine** [comment]
It should now work with the latest version on bioconda (see [pull request](https://github.com/bioconda/bioconda-recipes/pull/27308)).
I close the issue, thanks.

**Comment by andersgs** [comment]
This issue seems to have cropped up again. On version 0.4.3.

**Comment by fredericlemoine** [comment]
Hi @andersgs , 

Thank you for pointing this out! I made a mistake in the last update of the bioconda recipe... 
I updated the recipe (https://github.com/bioconda/bioconda-recipes/pull/37058) and it seems to work now, you can try with :

```
$ conda install -c bioconda gotree=0.4.3
$ gotree version
0.4.3
```
