### ISSUE TITLE
Bug of generate.

### ISSUE THREAD

**Issue by xiekunwhy** [evolbioinfo/gotree#17]
Hi,

No options to give tip number when using generate, I think there is a bug.

![image](https://user-images.githubusercontent.com/17738229/146312386-0b63d775-28a8-4b4a-937e-cb64b8507428.png)

Best,
Kun

**Comment by fredericlemoine** [comment]
Hi,

Indeed, the wrong help was displayed for the option "-o". I just corrected it. The option to give a number of tips (`-l`) is available in the sub-commands (yuletree, etc.)

Does it answer your question?

**Comment by fredericlemoine** [comment]
I close the issue, please feel free to reopen it if needed.
