### ISSUE TITLE
Issue installating goalign/gotree

### ISSUE THREAD

**Issue by cokelaer** [evolbioinfo/gotree#4]
While installing goalign using 
```
go get -u github.com/evolbioinfo/goalign/
```
I got this error message related to gotree::

    v0.3.0b: Could not introduce github.com/evolbioinfo/gotree@v0.3.0b, as its subpackage 
    github.com/evolbioinfo/gotree/models/protein is missing. (Package is required by (root).)

I had installed gotree succesfully before hand using 

```
go get -u github.com/evolbioinfo/gotree
```

**Comment by fredericlemoine** [comment]
There was a problem in some imports in goalign (https://github.com/evolbioinfo/goalign/commit/585c4fd45f422755109eeea4aad2e934692688ba), it should be solved now.
Tell me if it solves the issue.

**Comment by fredericlemoine** [comment]
I close the issue, feel free to reopen it if it still does not work
