### ISSUE TITLE
gotree new release

### ISSUE THREAD

**Issue by yuanning-li** [evolbioinfo/gotree#7]
Hey all:

I just noticed the recent commit of the function Monophyletic in stats option, and curious when will that be released in the binary file?

Li
Thanks

**Comment by fredericlemoine** [comment]
Hi Li, 

I have to check a couple of things before creating a new release, but I plan to do it soon, hopefully by the end of the week.

Frederic

**Comment by yuanning-li** [comment]
Thanks, looking forward with the new function

Li
Thanks

**Comment by fredericlemoine** [comment]
A new pre release is available here:
https://github.com/evolbioinfo/gotree/releases/tag/v0.4.0a
Best,
Frederic
