### ISSUE TITLE
nexus_parser.go:169:15: cannot use func literal (type func(string, string)) as type func(string, string) bool in argument to al.seqbag.Iterate

### ISSUE THREAD

**Issue by bjoernkjoshanssen** [evolbioinfo/gotree#8]
Got the above error when running
go get github.com/evolbioinfo/gotree/

**Comment by fredericlemoine** [comment]
Which version of go is installed? (`go version`)

**Comment by bjoernkjoshanssen** [comment]
1.13

**Comment by fredericlemoine** [comment]
Thanks for pointing out this issue. When using go get, the latest version of goalign dependencie is retrieved. In that version, the iterators have changed.
It should work now.

**Comment by bjoernkjoshanssen** [comment]
Thanks for the quick response, but I got the same error again just now...

**Comment by fredericlemoine** [comment]
I can't reproduce the issue, It may be due to a sync issue with go get, can you try with the `-u`option?

```
go get -u github.com/evolbioinfo/gotree
```

**Comment by bjoernkjoshanssen** [comment]
I tried that and now I get:
```
error: cannot open .git/FETCH_HEAD: Permission denied
package github.com/fatih/color: exit status 1
```

**Comment by fredericlemoine** [comment]
It seems something went wrong with permissions during the first go get...
You can try to remove problematic dependencies, for example:
```
rm -rf $GOPATH/github.com/fatih/color
```
and try again:
```
go get -u github.com/evolbioinfo/gotree
```
Or solve the permission issue, for example:
```
chown -R youruser:yourgroup $GOPATH/github.com/fatih/color/.git/
```

**Comment by bjoernkjoshanssen** [comment]
Now I get permission denied for
`go get -u github.com/fatih/color`
It seems that package is no longer maintained.

**Comment by fredericlemoine** [comment]
Indeed the package is no longer maintained, but it should not prevent a go get. There seems to be a permission problem with your go directory structure. Is `$GOPATH` in your home?

**Comment by bjoernkjoshanssen** [comment]
Thanks, got it to work now by switching to using a local machine rather than virtual machine.
